version: '3'
services:
  postgres:
        image: postgres:latest
        container_name: postgres
        ports:
            - "5432:5432"
        expose:
            - "5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: notionembed
        volumes:
            - postgres-data:/var/lib/postgresql/data
        restart: unless-stopped
  prisma-migrate:
        stdin_open: true 
        tty: true
        container_name: prisma-migrate
        build: 
          context: ./prisma
          dockerfile: ./Dockerfile 
        command: bash -c "npx prisma migrate reset && npx prisma migrate dev && npx prisma generate"
        environment:
            DATABASE_URL: postgresql://postgres:postgres@postgres:5432/notionembed?schema=public&connect_timeout=300
        depends_on:
            - postgres
        volumes:
          - ./:/src

volumes:
    postgres-data: