version: '3'
services:
  postgres:
        image: postgres:latest
        container_name: postgres
        ports:
            - "5432:5432"
        expose:
            - "5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: notionembed
        volumes:
            - postgres-data:/var/lib/postgresql/data
        restart: unless-stopped
  prisma-migrate:
        container_name: prisma-migrate
        build: 
          context: ./prisma
          dockerfile: Dockerfile 
        command: bash -c "cd ./prisma/prisma && npx prisma generate && npx prisma migrate dev --name=init"
        stdin_open: true 
        tty: true
        environment:
            DATABASE_URL: postgresql://postgres:postgres@192.168.1.74:5432/notionembed?schema=public&connect_timeout=300
        depends_on:
            - postgres
        volumes:
          - .:/prisma

volumes:
    postgres-data:
